In [43]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

In [34]:
iris_data = load_iris()
X = iris_data.data
y = iris_data.target

In [36]:
X.shape

(150, 4)

In [39]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [40]:
y.shape

(150,)

In [41]:
y[0]

0

In [5]:
lines = pd.read_csv('USA_Housing.csv')
lines.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  
0                          4.09     23086.800503  1.059034e+06  
1                          3.09     40173.072174  1.505891e+06  
2                          5.13     36882.159400  1.058988e+06  
3                          3.26     34310.242831  1.260617e+06  
4                          4.23     26354.109472  6.309435e+05

In [6]:
lines_np = np.loadtxt('USA_Housing.csv',delimiter=',',dtype='str')

In [9]:
lines_np[0]

array(['Avg. Area Income', 'Avg. Area House Age',
       'Avg. Area Number of Rooms', 'Avg. Area Number of Bedrooms',
       'Area Population', 'Price'], dtype='<U28')

In [12]:
lines.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price'],
      dtype='object')

In [13]:
','.join(lines_np[0][:-1])

'Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population'

In [21]:
lines_np[1:]

array([['79545.4585743168', '5.6828613216', '7.0091881428', '4.09',
        '23086.8005026865', '1059033.55787012'],
       ['79248.6424548257', '6.0028998083', '6.7308210191', '3.09',
        '40173.0721736448', '1505890.91484695'],
       ['61287.0671786568', '5.8658898403', '8.5127274304', '5.13',
        '36882.1593997046', '1058987.98787608'],
       ...,
       ['63390.6868855046', '7.2505906148', '4.8050809803', '2.13',
        '33266.1454896522', '1030729.58315229'],
       ['68001.331235087', '5.5343884162', '7.1301438643', '5.44',
        '42625.6201558509', '1198656.87240769'],
       ['65510.5818036662', '5.9923053073', '6.7923361044', '4.07',
        '46501.2838031416', '1298950.48026696']], dtype='<U28')

In [17]:
lines_np[1:].astype(float)

array([[7.95454586e+04, 5.68286132e+00, 7.00918814e+00, 4.09000000e+00,
        2.30868005e+04, 1.05903356e+06],
       [7.92486425e+04, 6.00289981e+00, 6.73082102e+00, 3.09000000e+00,
        4.01730722e+04, 1.50589091e+06],
       [6.12870672e+04, 5.86588984e+00, 8.51272743e+00, 5.13000000e+00,
        3.68821594e+04, 1.05898799e+06],
       ...,
       [6.33906869e+04, 7.25059061e+00, 4.80508098e+00, 2.13000000e+00,
        3.32661455e+04, 1.03072958e+06],
       [6.80013312e+04, 5.53438842e+00, 7.13014386e+00, 5.44000000e+00,
        4.26256202e+04, 1.19865687e+06],
       [6.55105818e+04, 5.99230531e+00, 6.79233610e+00, 4.07000000e+00,
        4.65012838e+04, 1.29895048e+06]])

In [42]:
ratio = .8
split = int(len(lines) * ratio)
np.random.seed(10)
lines = np.random.permutation(lines)
train,test = lines[:split],lines[split:]

In [45]:
scaler = StandardScaler()
scaler.fit(train)
train = scaler.transform(train)
test = scaler.transform(test)

In [52]:
train

array([[ 0.80952995, -0.71551591, -0.03989153,  0.42056418, -0.68067727,
        -0.32214064],
       [ 0.12132748, -0.99727435,  0.87976377, -0.65119549, -0.11120307,
         0.26931764],
       [-0.5630431 , -0.29742143, -0.12563275,  0.21757939,  0.04709977,
        -0.50493922],
       ...,
       [ 0.08941268, -0.62548994,  0.4219995 ,  1.95512916, -2.19503617,
        -1.11820591],
       [-2.63898855,  0.92205681, -0.40845475, -0.67555366,  0.98067475,
        -1.2264865 ],
       [-0.14639708,  0.92513613, -0.4960478 , -1.24391106, -0.88656616,
        -0.09253   ]])

In [51]:
train[:,:-1]

array([[ 0.80952995, -0.71551591, -0.03989153,  0.42056418, -0.68067727],
       [ 0.12132748, -0.99727435,  0.87976377, -0.65119549, -0.11120307],
       [-0.5630431 , -0.29742143, -0.12563275,  0.21757939,  0.04709977],
       ...,
       [ 0.08941268, -0.62548994,  0.4219995 ,  1.95512916, -2.19503617],
       [-2.63898855,  0.92205681, -0.40845475, -0.67555366,  0.98067475],
       [-0.14639708,  0.92513613, -0.4960478 , -1.24391106, -0.88656616]])

In [58]:
train[:,-1].shape

(4000,)

In [61]:
train[:,-1].flatten()

array([-0.32214064,  0.26931764, -0.50493922, ..., -1.11820591,
       -1.2264865 , -0.09253   ])

In [62]:
x_train,y_train = train[:,:-1],train[:,-1]
x_test,y_test = test[:,:-1],test[:,-1]

In [64]:
X = np.concatenate([x_train,np.ones((len(x_train),1))],axis=-1)

In [68]:
x_train[0]

array([ 0.80952995, -0.71551591, -0.03989153,  0.42056418, -0.68067727])

In [84]:
pd.DataFrame(x_train).head()

0         1         2         3         4
0  0.809530 -0.715516 -0.039892  0.420564 -0.680677
1  0.121327 -0.997274  0.879764 -0.651195 -0.111203
2 -0.563043 -0.297421 -0.125633  0.217579  0.047100
3 -2.792246  1.006244  1.980547  0.201341 -1.090658
4 -0.190521  1.641201  0.096581  0.412445  0.101819

In [66]:
pd.DataFrame(X).head()

0         1         2         3         4    5
0  0.809530 -0.715516 -0.039892  0.420564 -0.680677  1.0
1  0.121327 -0.997274  0.879764 -0.651195 -0.111203  1.0
2 -0.563043 -0.297421 -0.125633  0.217579  0.047100  1.0
3 -2.792246  1.006244  1.980547  0.201341 -1.090658  1.0
4 -0.190521  1.641201  0.096581  0.412445  0.101819  1.0

In [78]:
X.T[0]

array([ 0.80952995,  0.12132748, -0.5630431 , ...,  0.08941268,
       -2.63898855, -0.14639708])

In [77]:
X[0]

array([ 0.80952995, -0.71551591, -0.03989153,  0.42056418, -0.68067727,
        1.        ])

In [69]:
theta = np.linalg.inv(X.T @ X) @ X.T @ y_train

In [70]:
theta

array([ 6.48840249e-01,  4.66795843e-01,  3.40888040e-01,  8.52130018e-03,
        4.24951463e-01, -1.60496616e-14])

In [79]:
print('回归系数:',theta)

回归系数: [ 6.48840249e-01  4.66795843e-01  3.40888040e-01  8.52130018e-03
  4.24951463e-01 -1.60496616e-14]


In [80]:
np.random.permutation(5) # 

array([4, 2, 0, 3, 1])

In [81]:
np.random.permutation([i for i in range(5)])

array([3, 0, 1, 2, 4])

In [83]:
np.random.permutation??

Docstring:
permutation(x)

Randomly permute a sequence, or return a permuted range.

If `x` is a multi-dimensional array, it is only shuffled along its
first index.

.. note::
    New code should use the
    `~numpy.random.Generator.permutation`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
x : int or array_like
    If `x` is an integer, randomly permute ``np.arange(x)``.
    If `x` is an array, make a copy and shuffle the elements
    randomly.

Returns
-------
out : ndarray
    Permuted sequence or array range.

See Also
--------
random.Generator.permutation: which should be used for new code.

Examples
--------
>>> np.random.permutation(10)
array([1, 7, 4, 3, 0, 9, 2, 5, 8, 6]) # random

>>> np.random.permutation([1, 4, 9, 12, 15])
array([15,  1,  9,  4, 12]) # random

>>> arr = np.arange(9).reshape((3, 3))
>>> np.random.permutation(arr)
array([[6, 7, 8], # random
       [0, 1, 2],
       [3, 4, 5]])


In [85]:
theta.shape

(6,)

In [103]:
# 在测试集上使用回归系数进行预测
X_test = np.concatenate([x_test, np.ones((len(x_test), 1))], axis=-1)
y_pred = X_test @ theta
print(theta)

# 计算预测值和真实值之间的RMSE
rmse_loss = np.sqrt(np.square(y_test - y_pred).mean())
print('RMSE：', rmse_loss)

[ 6.48840249e-01  4.66795843e-01  3.40888040e-01  8.52130018e-03
  4.24951463e-01 -1.60496616e-14]
RMSE： 0.2789378697880506


In [102]:
from sklearn.linear_model import LinearRegression

# 初始化线性模型
linreg = LinearRegression()
# LinearRegression的方法中已经考虑了线性回归的常数项，所以无须再拼接1
linreg.fit(x_train, y_train)

# coef_是训练得到的回归系数，intercept_是常数项
print('回归系数：', linreg.coef_, linreg.intercept_)
y_pred = linreg.predict(x_test)

# 计算预测值和真实值之间的RMSE
rmse_loss = np.sqrt(np.square(y_test - y_pred).mean())
print('RMSE：', rmse_loss)

回归系数： [0.64884025 0.46679584 0.34088804 0.0085213  0.42495146] -1.6050849150851666e-14
RMSE： 0.2789378697880506
